---
# tasks file for tamay.composer

- name: "Check if composer is already installed"
  stat:
    path: "{{ composer_install_path }}/composer"
  register: _composer_state

- name: "Get installer signature"
  uri:
    url: https://composer.github.io/installer.sig
    return_content: yes
  register: _composer_signature
  when: not _composer_state.stat.exists

- name: "Download composer installer"
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    checksum: sha384:{{ _composer_signature.content }}
  when: not _composer_state.stat.exists

- name: "Install composer"
  command: php /tmp/composer-setup.php --install-dir={{ composer_install_path }} --filename=composer --quiet
  args:
    creates: "{{ composer_install_path }}/composer"
